### ISSUE TITLE
is there any plan to support more option when mount backend? for example,  Max TTL?

### ISSUE THREAD

**Issue by danielzhanghl** [seatgeek/hashi-helper#14]
hi, in the current code, only type/name are used when mount backend, as in parse_vault_mount.go

is there any plan to support more options? 

thanks

**Comment by jippi** [comment]
What options would that be? Please explain it with a use-case and a sample configuration HCL file as you would like it to be :)

**Comment by danielzhanghl** [comment]
for example, when configure PKI backend, need to specify the maxttl, to avoid the cert get expired too often, in vault docs, that use below command to do that:
vault mount-tune -max-lease-ttl=87600h pki

actually, it could be set when mount the backend, but this tool don't support that option.
vault   mount    pki max-lease-ttl=87600h

**Comment by jippi** [comment]
Have you tried 

```hcl
environment "production" {
  mount "pki" {
    type = "pki"

    config "" {
      max-lease-ttl  = "87600h"
    }
  }
}
```
