### ISSUE TITLE
improve documentation around 'encrypted file' in workflow examples

### ISSUE THREAD

**Issue by elijah** [seatgeek/hashi-helper#18]
As a potential user of hashi-helper, I would like for the documentation around encrypted file workflow to be more understandable.

In several places in the README.md, files are referred to as 'encrypted files', but there is little context given for how those files are encrypted - what is the tooling being used there?  Is it that keybase encrypt is intended to be used, or something else?  Or just that the vault-secret values stored in the files are somehow encrypted?

E.g., "The following can be stored in an encrypted file at production/apps/api-admin.hcl".

The code block following is in cleartext, and clearly the whole thing is meant to be crypto'ed, but no where else in the docs does it say *how* we should do that, or what the workflow is to make our locally-encrypted stuff usable with the vault-push-all or vault-push-secrets commands.

**Comment by josegonzalez** [comment]
@elijah What we do is we encrypt via [josegonzalez/sm](https://github.com/josegonzalez/sm). We have a small Makefile that decrypts all encrypted files - suffixed with `.sm` - and then we apply those files.

We only prescribe that you store an encrypted version of any secret, but:

- if you want to encrypt the whole thing as a single blob or individual files
- want to use a different encryption format than the one we use (kms-backed file encryption)
- do not want to store the `hashi-config` repo in git
- do not want to encrypt anything

Thats up to you to decide. Hope that helps :)
