### ISSUE TITLE
Configuring LDAP authentication engine & TTLs

### ISSUE THREAD

**Issue by patcable** [seatgeek/hashi-helper#25]
Hi! `hashi-helper` is super helpful. I'm looking to move a lot of my vault configuration over that way and am running into a few things.

## Configure LDAP Auth Engine
One thing that i'm not sure how to do as hashi-helper is right now is configure the LDAP authentication engine. I had tried something like:

```
environment "dev" {
    auth "ldap" {
        type = "ldap"
        config "" { # should write to /auth/ldap/config i imagine?
            url      = "ldap://blah"
            starttls = true
            #more ldap config bits here
        }
        duo "access" { # might? write to /auth/ldap/duo/access?
            host = "..."
            ikey = "..."
            skey = "..."
        }
        mfa_config "" { # /auth/ldap/mfa_config?
            type = "duo"
        }
        groups "vaultadmin" { # /auth/ldap/groups/vaultadmin?
            policies = "default,user-vaultadmin"
        }
    }
}
```
Is this something I'm going to have to wire up in `type_vault_auth.go` and `parse_vault_auth.go`? Or is there a generic "write key/value to place" resource thing i could use?

## Auth engine TTLs
Let's say I want to set default lease/max lease TTLs for a particular auth engine...
```
environment "dev" {
    auth "aws-ec2" {
        type = "aws-ec2"
        role "testrole" {
            bound_account_id          = "1234"
            policies                  = "default,pki"
            disallow_reauthentication = true
            role_tag                  = "vault_role"
        }
        defaultleasettl = "24h"
        maxleasettl     = "8w"
    }
}
```
I get this when i run hashi-helper:
```
* invalid key 'defaultleasettl' in line 10:9
* invalid key 'maxleasettl' in line 11:9
```
I see the struct in `type_vault_auth.go` includes those TTL values, but i dont think it gets mapped into that in `parse_vault_auth.go`.  Should I just tune this with the `mount` type instead?
```
    mount "auth/aws-ec2" {
        type              = "aws-ec2"
        default_lease_ttl = "1h"
        max_lease_ttl     = "1y"
    }
```

**Comment by patcable** [comment]
ah - okay. `secret` is fine with me for this - thanks! As far as default/maxTTL with underscores, I had tried that as well...

```
environment "dev" {
    auth "aws-ec2" {
        type              = "aws-ec2"
        default_lease_ttl = "1d"
        max_lease_ttl     = "8w"
        config "root" {
            access_key = "..."
            secret_key = "..."
            region = "..."
        }
        role "blah" {
            ...
        }
    }
}
```
and I got:
```
$ hashi-helper --environment dev --config-dir . vault-push-auth
1 error occurred:

* [./02_aws-ec2.hcl] 2 errors occurred:

* invalid key 'default_lease_ttl' in line 4:9
* invalid key 'max_lease_ttl' in line 5:9
```

**Comment by jippi** [comment]
thats a bug then :\ the fields exist in the struct, but seem like i only allow them within each `role`

**Comment by patcable** [comment]
yea - i noticed that. I tried to wire it up: https://github.com/seatgeek/hashi-helper/compare/master...patcable:master but no luck with that too. Made a new mount and it used default TTL settings. Didnt update existing TTL settings either.

**Comment by patcable** [comment]
Any idea on where i might have gone wrong on that code snippet?

**Comment by jippi** [comment]
the code responsible for writing it to Vault is [here](https://github.com/seatgeek/hashi-helper/blob/master/command/vault/auth_push.go#L62-L73) - i would inspect if `.data` is what we expect

**Comment by jippi** [comment]
oh, https://github.com/seatgeek/hashi-helper/blob/master/config/type_vault_auth.go#L11-L12

need to be have `json:"default_lease_ttl"` and `json:"max_lease_ttl"` annotations

**Comment by patcable** [comment]
I'm confused - how does it work for `type_vault_mount.go` which: also lacks annotations? (or has the functionality not been tested in the first place?)

**Comment by jippi** [comment]
ah, you are right, i also now (yay coffee!) found the issue

Need to add the fields to https://github.com/seatgeek/hashi-helper/blob/master/config/type_vault_auth.go#L18-L23 for it to work

**Comment by patcable** [comment]
So, I tried that in https://github.com/seatgeek/hashi-helper/compare/master...patcable:master and it didnt seem to work. Did I miss something in that commit?
