### ISSUE TITLE
Any chance of tagging v3.0.1?

### ISSUE THREAD

**Issue by oholiab** [seatgeek/hashi-helper#36]
This is off the back of #34 and #35, a tag containing these fixes would really save me having to mess about with building from a fork or pinning to a git sha for our internal package building CI :)

**Comment by jippi** [comment]
done in https://github.com/seatgeek/hashi-helper/releases/tag/v3.1.0

**Comment by oholiab** [comment]
You have just made my day’s work worlds easier, thank you so much!
