### ISSUE TITLE
Arrays resulting from lookups have unquoted members

### ISSUE THREAD

**Issue by oholiab** [seatgeek/hashi-helper#37]
I'm creating a PKI role that looks like:

```hcl
environment "all" {
  secret "/user-ca/roles/user" {
    "allowed_domains" = [[ lookup "all_engineers" ]]
    ...
  }
}
```

where `all_engineers` is populated by passing in a variables file of the format:

```json
{
  "all_engineers": [
    "joel",
    "jolene",
    ...
  ]
}
```

when I attempt to apply this configuration, I get the error `Could not format HCL file user_ca.hcl: At 3:26: unexpected token while parsing list: IDENT`

If I then (erroneously, but for debug purposes) put the templated lookup inside quotes, it's populated with a string literal of the result of the lookup (the array of usernames) whereby none of the members are quoted (which is consistent with the IDENT problem). This is counter to what I would expect to be the default behaviour to render as a list of quoted strings.

As a workaround I've had to hack together:
```hcl
    "allowed_domains" = [ [[ range $i, $name := lookup "all_engineers" ]][[if $i]] ,[[end]]"[[$name]]"[[end]] ]
```
which templates out the list as I want it formatted - this isn't ideal!

I'm happy to try to fix this myself but I'd appreciate guidance on where to look and whether you'd accept this patch in the first place.

**Comment by jippi** [comment]
tried to do `lookup "all_engineers" | toJSON` ?

**Comment by oholiab** [comment]
Yeah, I can't remember the exact error but it complained because `toJSON` was expecting a string indexed map rather than a straight up array of strings...
